/**************************************************************************************************\
 *** 
 *** Simulink model       : powerwindow_tl
 *** TargetLink subsystem : powerwindow_tl/PowerWindowController
 *** Codefile             : PowerWindowController.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2025-03-31 17:59:10
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1            PowerWindowController
 *** Sa2            PowerWindowController/detect_obstacle_endstop
 *** Spwlib1        PowerWindowController/validate_driver
 *** Spwlib1        PowerWindowController/validate_passenger
 *** Sa3            PowerWindowController/detect_obstacle_endstop/detect_endstop
 *** Sa4            PowerWindowController/detect_obstacle_endstop/detect_obstacle
 *** Spwlib2        PowerWindowController/validate_driver/check_down
 *** Spwlib3        PowerWindowController/validate_driver/check_up
 *** Spwlib4        PowerWindowController/validate_driver/mutually_exclusive
 *** Spwlib2        PowerWindowController/validate_passenger/check_down
 *** Spwlib3        PowerWindowController/validate_passenger/check_up
 *** Spwlib4        PowerWindowController/validate_passenger/mutually_exclusive
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** Ca0            powerwindow_tl                                  
 *** Ca1            PowerWindowController/control                   
 *** Ca2            PowerWindowController/control.systemNormal      
 *** Ca3            PowerWindowController/control.systemNormal.safe 
 *** Ca4            PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral                                  
 *** Ca5            PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerneutral                 
 *** Ca6            PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerDown                    
 *** Ca7            PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerDown.iniPassengerDown   
 *** Ca8            PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerDown.autoPassengerDown  
 *** Ca9            PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerDown.passengerDown      
 *** Ca10           PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerUp                      
 *** Ca11           PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerUp.iniPassengerUp       
 *** Ca12           PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerUp.PassengerUp          
 *** Ca13           PowerWindowController/control.systemNormal.safe
 ***                .driverNeutral.passengerUp.autoPassengerUp      
 *** Ca14           PowerWindowController/control.systemNormal.safe
 ***                .driverDown                                     
 *** Ca15           PowerWindowController/control.systemNormal.safe
 ***                .driverDown.iniDriverDown                       
 *** Ca16           PowerWindowController/control.systemNormal.safe
 ***                .driverDown.DriverDown                          
 *** Ca17           PowerWindowController/control.systemNormal.safe
 ***                .driverDown.autoDriverDown                      
 *** Ca18           PowerWindowController/control.systemNormal.safe
 ***                .driverUp                                       
 *** Ca19           PowerWindowController/control.systemNormal.safe
 ***                .driverUp.iniDriverUp                           
 *** Ca20           PowerWindowController/control.systemNormal.safe
 ***                .driverUp.DriverUp                              
 *** Ca21           PowerWindowController/control.systemNormal.safe
 ***                .driverUp.autoDriverUp                          
 *** Ca22           PowerWindowController/control.systemNormal.emer
 ***                gencyDown                                       
 *** Ca23           PowerWindowController/control.systemNormal.syst
 ***                emError                                         
 *** Ca24           PowerWindowController/control.obstacleDetection
 ***                Counter                                         
 *** 
 *** TargetLink version      : 22.1 from 02-Nov-2022
 *** Code generator version  : Build Id 22.1.0.27 from 2022-10-13 12:48:15
\**************************************************************************************************/

#ifndef POWERWINDOWCONTROLLER_C
#define POWERWINDOWCONTROLLER_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "PowerWindowController.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
CAL UInt8 position_endstop_top = 205 /* 0.4 */; /* LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 0.498046875 */

/**************************************************************************************************\
   MERGEABLE_CAL: mergeable calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
MERGEABLE_CAL UInt8 auto_down_time = 100;
MERGEABLE_CAL UInt8 auto_up_time = 100;
MERGEABLE_CAL UInt8 emergency_down_time = 100;

/**************************************************************************************************\
   MERGEABLE_GLOBAL: mergeable global variables (RAM) | Width: 8
\**************************************************************************************************/
MERGEABLE_GLOBAL Bool move_down_cmd;
MERGEABLE_GLOBAL Bool move_up_cmd;

/**************************************************************************************************\
   SFStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    8
\**************************************************************************************************/
static UInt8 Ca1_mode = 0;
static Bool Ca1_moveDown = 0;
static Bool Ca1_moveUp = 0;

/**************************************************************************************************\
   SFStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    N.A.
\**************************************************************************************************/
static struct tag_SIBFS_control_a_tp SIBFS_control_a = {
   0, /* Ca10_passengerUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca11_iniPassengerUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca12_PassengerUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca14_driverDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca15_iniDriverDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca16_DriverDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca18_driverUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca19_iniDriverUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca20_DriverUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca22_emergencyDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca24_obstacleDetectionCounter: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca2_systemNormal: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca3_safe: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca4_driverNeutral: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca5_passengerneutral: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca6_passengerDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca7_iniPassengerDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0 /* Ca8_autoPassengerDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
}; /* Description: Structure containing bitfields for Stateflow chart  */

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\**************************************************************************************************/
UInt16 Sa1_obstacle_position; /* LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 1 */
UInt16 Sa1_window_position; /* LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 1 */

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\**************************************************************************************************/
Bool Sa1_driver_down;
Bool Sa1_driver_neutral;
Bool Sa1_driver_up;
UInt8 Sa1_mode;
Bool Sa1_obstacle_detection;
Bool Sa1_passenger_down;
Bool Sa1_passenger_neutral;
Bool Sa1_passenger_up;

/**************************************************************************************************\
   SLStaticGlobal: Default storage class for global static variables | Width: 8
\**************************************************************************************************/
static Bool Sa3_detection__endstop_bottom;
static Bool Sa3_detection__endstop_top;
static Bool Sa4_detection_obstacle;
static Bool Spwlib1_validated_down_a;
static Bool Spwlib1_validated_down_b;
static Bool Spwlib1_validated_neutral_a;
static Bool Spwlib1_validated_neutral_b;
static Bool Spwlib1_validated_up_a;
static Bool Spwlib1_validated_up_b;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   STATIC_FCN: static function(s) (invisible for other module)
\**************************************************************************************************/
static void Ca1_control(void);

/**************************************************************************************************\
   StaticFcnSpecStep: Default function class for static model step functions
\**************************************************************************************************/
static void Sa2_detect_obstacle_endstop(void);

/**************************************************************************************************\
   StaticSFEntry: Default function class for static stateflow entry functions
\**************************************************************************************************/
static void Ca5_passengerneutral_en(void);

/**************************************************************************************************\
   StaticSFExit: Default function class for static stateflow exit functions
\**************************************************************************************************/
static void Ca10_passengerUp_ex(void);
static void Ca14_driverDown_ex(void);
static void Ca18_driverUp_ex(void);
static void Ca4_driverNeutral_ex(void);
static void Ca6_passengerDown_ex(void);

/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      validate_cmd
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      Bool               neutral             
 ***      Bool               up                  
 ***      Bool               down                
 ***      Bool               endstop_top         
 ***      Bool               endstop_bottom      
 ***      Bool *             Spwlib1_validated_neutral 
 ***      Bool *             Spwlib1_validated_up 
 ***      Bool *             Spwlib1_validated_down 
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void validate_cmd(Bool neutral, Bool up, Bool down, Bool endstop_top, Bool endstop_bottom, Bool *
  Spwlib1_validated_neutral, Bool * Spwlib1_validated_up, Bool * Spwlib1_validated_down)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   Bool Spwlib3_allow_action;

   /* Logical: PowerWindowController/validate_driver/check_down/allow_action
      # combined # TargetLink outport: PowerWindowController/validate_driver/validated_down
      # combined # Logical: PowerWindowController/validate_driver/check_down/not */
   *Spwlib1_validated_down = down && (!(endstop_bottom));

   /* Logical: PowerWindowController/validate_driver/check_up/allow_action
      # combined # Logical: PowerWindowController/validate_driver/check_up/not */
   Spwlib3_allow_action = up && (!(endstop_top));

   /* Logical: PowerWindowController/validate_driver/mutually_exclusive/up_after_down
      # combined # TargetLink outport: PowerWindowController/validate_driver/validated_up
      # combined # Logical: PowerWindowController/validate_driver/mutually_exclusive/not_down
      # combined # TargetLink outport: PowerWindowController/validate_driver/validated_down */
   *Spwlib1_validated_up = Spwlib3_allow_action && (!(*Spwlib1_validated_down));

   /* TargetLink outport: PowerWindowController/validate_driver/validated_neutral
      # combined # Logical: PowerWindowController/validate_driver/mutually_exclusive/default_neutral
      # combined # Logical: PowerWindowController/validate_driver/mutually_exclusive/not_up1
      # combined # Logical: PowerWindowController/validate_driver/mutually_exclusive/neutral_after_u
      p
      # combined # Logical: PowerWindowController/validate_driver/mutually_exclusive/not_up
      # combined # TargetLink outport: PowerWindowController/validate_driver/validated_up
      # combined # TargetLink outport: PowerWindowController/validate_driver/validated_down */
   *Spwlib1_validated_neutral = (neutral && (!(*Spwlib1_validated_up))) ||
    ((!(Spwlib3_allow_action)) && (!(*Spwlib1_validated_down)));
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      PowerWindowController
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void PowerWindowController(void)
{
   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
   */
   static Bool X_Sa1_last_move_up_cmd = 0;

   /* Unit delay: PowerWindowController/last_move_up_cmd */
   move_up_cmd = X_Sa1_last_move_up_cmd;

   /* call of function: PowerWindowController/detect_obstacle_endstop */
   Sa2_detect_obstacle_endstop();

   /* call of function: PowerWindowController/validate_driver */
   validate_cmd(Sa1_driver_neutral, Sa1_driver_up, Sa1_driver_down, Sa3_detection__endstop_top,
    Sa3_detection__endstop_bottom, &Spwlib1_validated_neutral_a, &Spwlib1_validated_up_a,
    &Spwlib1_validated_down_a);

   /* call of function: PowerWindowController/validate_passenger */
   validate_cmd(Sa1_passenger_neutral, Sa1_passenger_up, Sa1_passenger_down,
    Sa3_detection__endstop_top, Sa3_detection__endstop_bottom, &Spwlib1_validated_neutral_b,
    &Spwlib1_validated_up_b, &Spwlib1_validated_down_b);

   /* call of function: PowerWindowController/control */
   Ca1_control();

   /* Unit delay: PowerWindowController/last_move_up_cmd */
   X_Sa1_last_move_up_cmd = Ca1_moveUp;

   /* TargetLink outport: PowerWindowController/move_down_cmd */
   move_down_cmd = Ca1_moveDown;

   /* TargetLink outport: PowerWindowController/move_up_cmd */
   move_up_cmd = Ca1_moveUp;

   /* TargetLink outport: PowerWindowController/mode */
   Sa1_mode = Ca1_mode;

   /* TargetLink outport: PowerWindowController/obstacle_detection */
   Sa1_obstacle_detection = Sa4_detection_obstacle;
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca1_control
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca1_control(void)
{
   /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
   */
   static UInt8 Ca1_control_ctr = 0;
   static UInt8 Ca1_control_ctr_a = 0;
   static UInt8 Ca1_control_ctr_b = 0;

   if (Ca1_control_ctr < 255) {
      Ca1_control_ctr = Ca1_control_ctr + 1;
   }
   if (Ca1_control_ctr_a < 255) {
      Ca1_control_ctr_a = Ca1_control_ctr_a + 1;
   }
   if (Ca1_control_ctr_b < 255) {
      Ca1_control_ctr_b = Ca1_control_ctr_b + 1;
   }

   /* Begin execution of chart PowerWindowController/control */
   if (SIBFS_control_a.Ca2_systemNormal) {
      /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width:
       8 */
      static UInt8 Ca1_counter = 0;

      /* Begin execution of state PowerWindowController/control.systemNormal */
      if (SIBFS_control_a.Ca3_safe) {
         /* Begin execution of state PowerWindowController/control.systemNormal.safe */
         if (Ca1_counter >= 100) {
            /* State transition from PowerWindowController/control.systemNormal.safe to PowerWindowC
               ontroller/control.systemNormal.systemError */
            if (SIBFS_control_a.Ca4_driverNeutral) {
               Ca4_driverNeutral_ex();
            }
            else {
               if (SIBFS_control_a.Ca14_driverDown) {
                  Ca14_driverDown_ex();
               }
               else {
                  if (SIBFS_control_a.Ca18_driverUp) {
                     Ca18_driverUp_ex();
                  }
               }
            }
            SIBFS_control_a.Ca3_safe = 0;
            Ca1_mode = 100;
            Ca1_moveUp = 0;
            Ca1_moveDown = 0;
         }
         else {
            if (SIBFS_control_a.Ca4_driverNeutral) {
               /* Begin execution of state PowerWindowController/control.systemNormal.safe.driverNeu
                  tral */
               if (Sa4_detection_obstacle) {
                  /* State transition from PowerWindowController/control.systemNormal.safe.driverNeu
                     tral to PowerWindowController/control.systemNormal.emergencyDown */
                  Ca4_driverNeutral_ex();
                  SIBFS_control_a.Ca3_safe = 0;
                  Ca1_control_ctr = 0;
                  SIBFS_control_a.Ca22_emergencyDown = 1;
                  Ca1_moveUp = 0;
                  Ca1_moveDown = 1;
                  Ca1_mode = 5;
               }
               else {
                  if (Spwlib1_validated_up_a) {
                     /* State transition from PowerWindowController/control.systemNormal.safe.driver
                        Neutral to PowerWindowController/control.systemNormal.safe.driverUp.iniDrive
                        rUp */
                     Ca4_driverNeutral_ex();
                     SIBFS_control_a.Ca18_driverUp = 1;
                     Ca1_moveUp = 1;
                     Ca1_control_ctr_b = 0;
                     SIBFS_control_a.Ca19_iniDriverUp = 1;
                     Ca1_mode = 1;
                  }
                  else {
                     if (Spwlib1_validated_down_a) {
                        /* State transition from PowerWindowController/control.systemNormal.safe.dri
                           verNeutral to PowerWindowController/control.systemNormal.safe.driverDown.
                           iniDriverDown */
                        Ca4_driverNeutral_ex();
                        SIBFS_control_a.Ca14_driverDown = 1;
                        Ca1_moveDown = 1;
                        Ca1_control_ctr_b = 0;
                        SIBFS_control_a.Ca15_iniDriverDown = 1;
                        Ca1_mode = 2;
                     }
                     else {
                        if (SIBFS_control_a.Ca5_passengerneutral) {
                           /* Begin execution of state PowerWindowController/control.systemNormal.sa
                              fe.driverNeutral.passengerneutral */
                           if (Spwlib1_validated_up_b) {
                              /* State transition from PowerWindowController/control.systemNormal.sa
                                 fe.driverNeutral.passengerneutral to PowerWindowController/control.
                                 systemNormal.safe.driverNeutral.passengerUp.iniPassengerUp */
                              SIBFS_control_a.Ca5_passengerneutral = 0;
                              SIBFS_control_a.Ca10_passengerUp = 1;
                              Ca1_moveUp = 1;
                              Ca1_control_ctr_a = 0;
                              SIBFS_control_a.Ca11_iniPassengerUp = 1;
                              Ca1_mode = 1;
                           }
                           else {
                              if (Spwlib1_validated_down_b) {
                                 /* State transition from PowerWindowController/control.systemNormal
                                    .safe.driverNeutral.passengerneutral to PowerWindowController/co
                                    ntrol.systemNormal.safe.driverNeutral.passengerDown.iniPassenger
                                    Down */
                                 SIBFS_control_a.Ca5_passengerneutral = 0;
                                 SIBFS_control_a.Ca6_passengerDown = 1;
                                 Ca1_moveDown = 1;
                                 Ca1_control_ctr_a = 0;
                                 SIBFS_control_a.Ca7_iniPassengerDown = 1;
                                 Ca1_mode = 2;
                              }
                           }
                           /* End execution of state PowerWindowController/control.systemNormal.safe
                              .driverNeutral.passengerneutral */
                        }
                        else {
                           if (SIBFS_control_a.Ca6_passengerDown) {
                              /* Begin execution of state PowerWindowController/control.systemNormal
                                 .safe.driverNeutral.passengerDown */
                              if (Sa3_detection__endstop_bottom) {
                                 /* State transition from PowerWindowController/control.systemNormal
                                    .safe.driverNeutral.passengerDown to PowerWindowController/contr
                                    ol.systemNormal.safe.driverNeutral.passengerneutral */
                                 Ca6_passengerDown_ex();
                                 Ca5_passengerneutral_en();
                              }
                              else {
                                 if (Spwlib1_validated_up_b) {
                                    /* State transition from PowerWindowController/control.systemNor
                                       mal.safe.driverNeutral.passengerDown to PowerWindowController
                                       /control.systemNormal.safe.driverNeutral.passengerUp.Passenge
                                       rUp */
                                    Ca6_passengerDown_ex();
                                    SIBFS_control_a.Ca10_passengerUp = 1;
                                    Ca1_moveUp = 1;
                                    SIBFS_control_a.Ca12_PassengerUp = 1;
                                    Ca1_mode = 1;
                                 }
                                 else {
                                    if (SIBFS_control_a.Ca7_iniPassengerDown) {
                                       /* Begin execution of state PowerWindowController/control.sys
                                          temNormal.safe.driverNeutral.passengerDown.iniPassengerDow
                                          n */
                                       if (Ca1_control_ctr_a >= auto_down_time) {
                                          if (Spwlib1_validated_neutral_b) {
                                          /* State transition to PowerWindowController/control.syste
                                          mNormal.safe.driverNeutral.passengerDown.autoPassengerD
                                          own */
                                          SIBFS_control_a.Ca7_iniPassengerDown = 0;
                                          SIBFS_control_a.Ca8_autoPassengerDown = 1;
                                          Ca1_mode = 4;
                                          }
                                          else {
                                          /* State transition to PowerWindowController/control.syste
                                          mNormal.safe.driverNeutral.passengerDown.passengerDown */
                                          SIBFS_control_a.Ca7_iniPassengerDown = 0;
                                          Ca1_mode = 2;
                                          }
                                       }
                                       /* End execution of state PowerWindowController/control.syste
                                          mNormal.safe.driverNeutral.passengerDown.iniPassengerDown
                                          */
                                    }
                                    else {
                                       if (!(SIBFS_control_a.Ca8_autoPassengerDown)) {
                                          /* Begin execution of state PowerWindowController/control.
                                          systemNormal.safe.driverNeutral.passengerDown.passenger
                                          Down */
                                          if (Spwlib1_validated_neutral_b) {
                                          /* State transition from PowerWindowController/control.sys
                                          temNormal.safe.driverNeutral.passengerDown.passengerDow
                                          n to PowerWindowController/control.systemNormal.safe.dr
                                          iverNeutral.passengerneutral */
                                          Ca1_moveDown = 0;
                                          SIBFS_control_a.Ca6_passengerDown = 0;
                                          Ca5_passengerneutral_en();
                                          }
                                          /* End execution of state PowerWindowController/control.sy
                                          stemNormal.safe.driverNeutral.passengerDown.passengerDo
                                          wn */
                                       }
                                    }
                                 }
                              }
                              /* End execution of state PowerWindowController/control.systemNormal.s
                                 afe.driverNeutral.passengerDown */
                           }
                           else {
                              if (SIBFS_control_a.Ca10_passengerUp) {
                                 /* Begin execution of state PowerWindowController/control.systemNor
                                    mal.safe.driverNeutral.passengerUp */
                                 if (Spwlib1_validated_down_b) {
                                    /* State transition from PowerWindowController/control.systemNor
                                       mal.safe.driverNeutral.passengerUp to PowerWindowController/c
                                       ontrol.systemNormal.safe.driverNeutral.passengerDown.passenge
                                       rDown */
                                    Ca10_passengerUp_ex();
                                    SIBFS_control_a.Ca6_passengerDown = 1;
                                    Ca1_moveDown = 1;
                                    Ca1_mode = 2;
                                 }
                                 else {
                                    if (Sa3_detection__endstop_top) {
                                       /* State transition from PowerWindowController/control.system
                                          Normal.safe.driverNeutral.passengerUp to PowerWindowContro
                                          ller/control.systemNormal.safe.driverNeutral.passengerneut
                                          ral */
                                       Ca10_passengerUp_ex();
                                       Ca5_passengerneutral_en();
                                    }
                                    else {
                                       if (SIBFS_control_a.Ca11_iniPassengerUp) {
                                          /* Begin execution of state PowerWindowController/control.
                                          systemNormal.safe.driverNeutral.passengerUp.iniPassenge
                                          rUp */
                                          if (Ca1_control_ctr_a >= auto_up_time) {
                                          if (Spwlib1_validated_neutral_b) {
                                          /* State transition to PowerWindowController/control.syste
                                          mNormal.safe.driverNeutral.passengerUp.autoPassengerUp */
                                          SIBFS_control_a.Ca11_iniPassengerUp = 0;
                                          Ca1_mode = 3;
                                          }
                                          else {
                                          /* State transition to PowerWindowController/control.syste
                                          mNormal.safe.driverNeutral.passengerUp.PassengerUp */
                                          SIBFS_control_a.Ca11_iniPassengerUp = 0;
                                          SIBFS_control_a.Ca12_PassengerUp = 1;
                                          Ca1_mode = 1;
                                          }
                                          }
                                          /* End execution of state PowerWindowController/control.sy
                                          stemNormal.safe.driverNeutral.passengerUp.iniPassengerU
                                          p */
                                       }
                                       else {
                                          if (SIBFS_control_a.Ca12_PassengerUp) {
                                          /* Begin execution of state PowerWindowController/control.
                                          systemNormal.safe.driverNeutral.passengerUp.PassengerUp */
                                          if (Spwlib1_validated_neutral_b) {
                                          /* State transition from PowerWindowController/control.sys
                                          temNormal.safe.driverNeutral.passengerUp.PassengerUp to
                                          PowerWindowController/control.systemNormal.safe.driver
                                          Neutral.passengerneutral */
                                          SIBFS_control_a.Ca12_PassengerUp = 0;
                                          Ca1_moveUp = 0;
                                          SIBFS_control_a.Ca10_passengerUp = 0;
                                          Ca5_passengerneutral_en();
                                          }
                                          /* End execution of state PowerWindowController/control.sy
                                          stemNormal.safe.driverNeutral.passengerUp.PassengerUp */
                                          }
                                       }
                                    }
                                 }
                                 /* End execution of state PowerWindowController/control.systemNorma
                                    l.safe.driverNeutral.passengerUp */
                              }
                           }
                        }
                     }
                  }
               }
               /* End execution of state PowerWindowController/control.systemNormal.safe.driverNeutr
                  al */
            }
            else {
               if (SIBFS_control_a.Ca14_driverDown) {
                  /* Begin execution of state PowerWindowController/control.systemNormal.safe.driver
                     Down */
                  if (Sa3_detection__endstop_bottom) {
                     /* State transition from PowerWindowController/control.systemNormal.safe.driver
                        Down to PowerWindowController/control.systemNormal.safe.driverNeutral */
                     Ca14_driverDown_ex();
                     SIBFS_control_a.Ca4_driverNeutral = 1;

                     /* State transition to PowerWindowController/control.systemNormal.safe.driverNe
                        utral.passengerneutral */
                     Ca5_passengerneutral_en();
                  }
                  else {
                     if (Spwlib1_validated_up_a) {
                        /* State transition from PowerWindowController/control.systemNormal.safe.dri
                           verDown to PowerWindowController/control.systemNormal.safe.driverUp.Drive
                           rUp */
                        Ca14_driverDown_ex();
                        SIBFS_control_a.Ca18_driverUp = 1;
                        Ca1_moveUp = 1;
                        SIBFS_control_a.Ca20_DriverUp = 1;
                        Ca1_mode = 1;
                     }
                     else {
                        if (SIBFS_control_a.Ca15_iniDriverDown) {
                           /* Begin execution of state PowerWindowController/control.systemNormal.sa
                              fe.driverDown.iniDriverDown */
                           if (Ca1_control_ctr_b >= auto_down_time) {
                              if (Spwlib1_validated_neutral_a) {
                                 /* State transition to PowerWindowController/control.systemNormal.s
                                    afe.driverDown.autoDriverDown */
                                 SIBFS_control_a.Ca15_iniDriverDown = 0;
                                 Ca1_mode = 4;
                              }
                              else {
                                 /* State transition to PowerWindowController/control.systemNormal.s
                                    afe.driverDown.DriverDown */
                                 SIBFS_control_a.Ca15_iniDriverDown = 0;
                                 SIBFS_control_a.Ca16_DriverDown = 1;
                                 Ca1_mode = 2;
                              }
                           }
                           /* End execution of state PowerWindowController/control.systemNormal.safe
                              .driverDown.iniDriverDown */
                        }
                        else {
                           if (SIBFS_control_a.Ca16_DriverDown) {
                              /* Begin execution of state PowerWindowController/control.systemNormal
                                 .safe.driverDown.DriverDown */
                              if (Spwlib1_validated_neutral_a) {
                                 /* State transition from PowerWindowController/control.systemNormal
                                    .safe.driverDown.DriverDown to PowerWindowController/control.sys
                                    temNormal.safe.driverNeutral */
                                 SIBFS_control_a.Ca16_DriverDown = 0;
                                 Ca1_moveDown = 0;
                                 SIBFS_control_a.Ca14_driverDown = 0;
                                 SIBFS_control_a.Ca4_driverNeutral = 1;

                                 /* State transition to PowerWindowController/control.systemNormal.s
                                    afe.driverNeutral.passengerneutral */
                                 Ca5_passengerneutral_en();
                              }
                              /* End execution of state PowerWindowController/control.systemNormal.s
                                 afe.driverDown.DriverDown */
                           }
                        }
                     }
                  }
                  /* End execution of state PowerWindowController/control.systemNormal.safe.driverDo
                     wn */
               }
               else {
                  if (SIBFS_control_a.Ca18_driverUp) {
                     /* Begin execution of state PowerWindowController/control.systemNormal.safe.dri
                        verUp */
                     if (Spwlib1_validated_down_a) {
                        /* State transition from PowerWindowController/control.systemNormal.safe.dri
                           verUp to PowerWindowController/control.systemNormal.safe.driverDown.Drive
                           rDown */
                        Ca18_driverUp_ex();
                        SIBFS_control_a.Ca14_driverDown = 1;
                        Ca1_moveDown = 1;
                        SIBFS_control_a.Ca16_DriverDown = 1;
                        Ca1_mode = 2;
                     }
                     else {
                        if (Sa3_detection__endstop_top) {
                           /* State transition from PowerWindowController/control.systemNormal.safe.
                              driverUp to PowerWindowController/control.systemNormal.safe.driverNeut
                              ral */
                           Ca18_driverUp_ex();
                           SIBFS_control_a.Ca4_driverNeutral = 1;

                           /* State transition to PowerWindowController/control.systemNormal.safe.dr
                              iverNeutral.passengerneutral */
                           Ca5_passengerneutral_en();
                        }
                        else {
                           if (SIBFS_control_a.Ca19_iniDriverUp) {
                              /* Begin execution of state PowerWindowController/control.systemNormal
                                 .safe.driverUp.iniDriverUp */
                              if (Ca1_control_ctr_b >= auto_up_time) {
                                 if (Spwlib1_validated_neutral_a) {
                                    /* State transition to PowerWindowController/control.systemNorma
                                       l.safe.driverUp.autoDriverUp */
                                    SIBFS_control_a.Ca19_iniDriverUp = 0;
                                    Ca1_mode = 3;
                                 }
                                 else {
                                    /* State transition to PowerWindowController/control.systemNorma
                                       l.safe.driverUp.DriverUp */
                                    SIBFS_control_a.Ca19_iniDriverUp = 0;
                                    SIBFS_control_a.Ca20_DriverUp = 1;
                                    Ca1_mode = 1;
                                 }
                              }
                              /* End execution of state PowerWindowController/control.systemNormal.s
                                 afe.driverUp.iniDriverUp */
                           }
                           else {
                              if (SIBFS_control_a.Ca20_DriverUp) {
                                 /* Begin execution of state PowerWindowController/control.systemNor
                                    mal.safe.driverUp.DriverUp */
                                 if (Spwlib1_validated_neutral_a) {
                                    /* State transition from PowerWindowController/control.systemNor
                                       mal.safe.driverUp.DriverUp to PowerWindowController/control.s
                                       ystemNormal.safe.driverNeutral */
                                    SIBFS_control_a.Ca20_DriverUp = 0;
                                    Ca1_moveUp = 0;
                                    SIBFS_control_a.Ca18_driverUp = 0;
                                    SIBFS_control_a.Ca4_driverNeutral = 1;

                                    /* State transition to PowerWindowController/control.systemNorma
                                       l.safe.driverNeutral.passengerneutral */
                                    Ca5_passengerneutral_en();
                                 }
                                 /* End execution of state PowerWindowController/control.systemNorma
                                    l.safe.driverUp.DriverUp */
                              }
                           }
                        }
                     }
                     /* End execution of state PowerWindowController/control.systemNormal.safe.drive
                        rUp */
                  }
               }
            }
         }
         /* End execution of state PowerWindowController/control.systemNormal.safe */
      }
      else {
         if (SIBFS_control_a.Ca22_emergencyDown) {
            /* Begin execution of state PowerWindowController/control.systemNormal.emergencyDown */
            if (Ca1_counter >= 100) {
               /* State transition from PowerWindowController/control.systemNormal.emergencyDown to 
                  PowerWindowController/control.systemNormal.systemError */
               SIBFS_control_a.Ca22_emergencyDown = 0;
               Ca1_mode = 100;
               Ca1_moveUp = 0;
               Ca1_moveDown = 0;
            }
            else {
               if (Sa3_detection__endstop_bottom || (Ca1_control_ctr >= emergency_down_time)) {
                  /* State transition from PowerWindowController/control.systemNormal.emergencyDown 
                     to PowerWindowController/control.systemNormal.safe.driverNeutral.passengerneutr
                     al */
                  SIBFS_control_a.Ca22_emergencyDown = 0;
                  SIBFS_control_a.Ca3_safe = 1;
                  SIBFS_control_a.Ca4_driverNeutral = 1;
                  Ca5_passengerneutral_en();
               }
            }
            /* End execution of state PowerWindowController/control.systemNormal.emergencyDown */
         }
      }

      /* End execution of state PowerWindowController/control.systemNormal */
      if (SIBFS_control_a.Ca24_obstacleDetectionCounter) {
         /* Begin execution of state PowerWindowController/control.obstacleDetectionCounter */
         if (!(Sa4_detection_obstacle)) {
            /* State transition from PowerWindowController/control.obstacleDetectionCounter to Power
               WindowController/control.obstacleDetectionCounter */
            Ca1_counter = 0;
         }
         else {
            /* State transition from PowerWindowController/control.obstacleDetectionCounter to Power
               WindowController/control.obstacleDetectionCounter */
            Ca1_counter = Ca1_counter + 1;
         }
         /* End execution of state PowerWindowController/control.obstacleDetectionCounter */
      }
   }
   else {
      /* State transition to PowerWindowController/control.systemNormal */
      SIBFS_control_a.Ca2_systemNormal = 1;

      /* State transition to PowerWindowController/control.systemNormal.safe */
      SIBFS_control_a.Ca3_safe = 1;

      /* State transition to PowerWindowController/control.systemNormal.safe.driverNeutral */
      SIBFS_control_a.Ca4_driverNeutral = 1;

      /* State transition to PowerWindowController/control.systemNormal.safe.driverNeutral.passenger
         neutral */
      Ca5_passengerneutral_en();
      SIBFS_control_a.Ca24_obstacleDetectionCounter = 1;
   }
   /* End execution of chart PowerWindowController/control */
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Sa2_detect_obstacle_endstop
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Sa2_detect_obstacle_endstop(void)
{
   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
   */
   static Bool X_Sa4_Unit_Delay = 0;

   /* Relational: PowerWindowController/detect_obstacle_endstop/detect_endstop/detection_ endstop_bo
      ttom */
   Sa3_detection__endstop_bottom = Sa1_window_position <= 0;

   /* Relational: PowerWindowController/detect_obstacle_endstop/detect_endstop/detection_ endstop_to
      p */
   Sa3_detection__endstop_top = Sa1_window_position >= ((UInt16) position_endstop_top);

   /* Unit delay: PowerWindowController/detect_obstacle_endstop/detect_obstacle/Unit Delay */
   move_up_cmd = X_Sa4_Unit_Delay;
   X_Sa4_Unit_Delay = move_up_cmd;

   /* Logical: PowerWindowController/detect_obstacle_endstop/detect_obstacle/detection_obstacle
      # combined # Logical: PowerWindowController/detect_obstacle_endstop/detect_obstacle/obstacle _
      om_off
      # combined # Relational: PowerWindowController/detect_obstacle_endstop/detect_obstacle/Operato
      r1
      # combined # Relational: PowerWindowController/detect_obstacle_endstop/detect_obstacle/Operato
      r */
   Sa4_detection_obstacle = (Sa1_window_position > Sa1_obstacle_position) && (Sa1_obstacle_position
    > 0) && move_up_cmd;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca5_passengerneutral_en
 *** 
 ***  DESCRIPTION:
 ***      Entry function of state: PowerWindowController/control.systemNormal.safe.driverNeutral.pas
 ***      sengerneutral
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca5_passengerneutral_en(void)
{
   SIBFS_control_a.Ca5_passengerneutral = 1;
   Ca1_moveUp = 0;
   Ca1_moveDown = 0;
   Ca1_mode = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca10_passengerUp_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: PowerWindowController/control.systemNormal.safe.driverNeutral.pass
 ***      engerUp
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca10_passengerUp_ex(void)
{
   if (SIBFS_control_a.Ca11_iniPassengerUp) {
      SIBFS_control_a.Ca11_iniPassengerUp = 0;
   }
   else {
      if (SIBFS_control_a.Ca12_PassengerUp) {
         SIBFS_control_a.Ca12_PassengerUp = 0;
      }
   }
   Ca1_moveUp = 0;
   SIBFS_control_a.Ca10_passengerUp = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca14_driverDown_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: PowerWindowController/control.systemNormal.safe.driverDown
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca14_driverDown_ex(void)
{
   if (SIBFS_control_a.Ca15_iniDriverDown) {
      SIBFS_control_a.Ca15_iniDriverDown = 0;
   }
   else {
      if (SIBFS_control_a.Ca16_DriverDown) {
         SIBFS_control_a.Ca16_DriverDown = 0;
      }
   }
   Ca1_moveDown = 0;
   SIBFS_control_a.Ca14_driverDown = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca18_driverUp_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: PowerWindowController/control.systemNormal.safe.driverUp
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca18_driverUp_ex(void)
{
   if (SIBFS_control_a.Ca19_iniDriverUp) {
      SIBFS_control_a.Ca19_iniDriverUp = 0;
   }
   else {
      if (SIBFS_control_a.Ca20_DriverUp) {
         SIBFS_control_a.Ca20_DriverUp = 0;
      }
   }
   Ca1_moveUp = 0;
   SIBFS_control_a.Ca18_driverUp = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca4_driverNeutral_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: PowerWindowController/control.systemNormal.safe.driverNeutral
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca4_driverNeutral_ex(void)
{
   if (SIBFS_control_a.Ca5_passengerneutral) {
      SIBFS_control_a.Ca5_passengerneutral = 0;
   }
   else {
      if (SIBFS_control_a.Ca6_passengerDown) {
         Ca6_passengerDown_ex();
      }
      else {
         if (SIBFS_control_a.Ca10_passengerUp) {
            Ca10_passengerUp_ex();
         }
      }
   }
   SIBFS_control_a.Ca4_driverNeutral = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca6_passengerDown_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: PowerWindowController/control.systemNormal.safe.driverNeutral.pass
 ***      engerDown
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca6_passengerDown_ex(void)
{
   if (SIBFS_control_a.Ca7_iniPassengerDown) {
      SIBFS_control_a.Ca7_iniPassengerDown = 0;
   }
   else {
      if (SIBFS_control_a.Ca8_autoPassengerDown) {
         SIBFS_control_a.Ca8_autoPassengerDown = 0;
      }
   }
   Ca1_moveDown = 0;
   SIBFS_control_a.Ca6_passengerDown = 0;
}

#ifdef __cplusplus
}
#endif

#endif /* POWERWINDOWCONTROLLER_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
