/**************************************************************************************************\
 *** 
 *** Simulink model       : powerwindow_tl
 *** TargetLink subsystem : powerwindow_tl/PowerWindowController
 *** Codefile             : PowerWindowController.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2025-03-31 17:59:10
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 22.1 from 02-Nov-2022
 *** Code generator version  : Build Id 22.1.0.27 from 2022-10-13 12:48:15
\**************************************************************************************************/

#ifndef POWERWINDOWCONTROLLER_H
#define POWERWINDOWCONTROLLER_H

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "tl_defines_a.h"
#include "tl_basetypes.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

struct tag_SIBFS_control_a_tp {
   unsigned int Ca10_passengerUp : 1;
   unsigned int Ca11_iniPassengerUp : 1;
   unsigned int Ca12_PassengerUp : 1;
   unsigned int Ca14_driverDown : 1;
   unsigned int Ca15_iniDriverDown : 1;
   unsigned int Ca16_DriverDown : 1;
   unsigned int Ca18_driverUp : 1;
   unsigned int Ca19_iniDriverUp : 1;
   unsigned int Ca20_DriverUp : 1;
   unsigned int Ca22_emergencyDown : 1;
   unsigned int Ca24_obstacleDetectionCounter : 1;
   unsigned int Ca2_systemNormal : 1;
   unsigned int Ca3_safe : 1;
   unsigned int Ca4_driverNeutral : 1;
   unsigned int Ca5_passengerneutral : 1;
   unsigned int Ca6_passengerDown : 1;
   unsigned int Ca7_iniPassengerDown : 1;
   unsigned int Ca8_autoPassengerDown : 1;
}; /* Description: Type of structure containing bitfields for Stateflow chart  */

/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
extern CAL UInt8 position_endstop_top; /* LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 0.498046875 */

/**************************************************************************************************\
   MERGEABLE_CAL: mergeable calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
extern MERGEABLE_CAL UInt8 auto_down_time;
extern MERGEABLE_CAL UInt8 auto_up_time;
extern MERGEABLE_CAL UInt8 emergency_down_time;

/**************************************************************************************************\
   MERGEABLE_GLOBAL: mergeable global variables (RAM) | Width: 8
\**************************************************************************************************/
extern MERGEABLE_GLOBAL Bool move_down_cmd;
extern MERGEABLE_GLOBAL Bool move_up_cmd;

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\**************************************************************************************************/
extern UInt16 Sa1_obstacle_position; /* LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 1 */
extern UInt16 Sa1_window_position; /* LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 1 */

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\**************************************************************************************************/
extern Bool Sa1_driver_down;
extern Bool Sa1_driver_neutral;
extern Bool Sa1_driver_up;
extern UInt8 Sa1_mode;
extern Bool Sa1_obstacle_detection;
extern Bool Sa1_passenger_down;
extern Bool Sa1_passenger_neutral;
extern Bool Sa1_passenger_up;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GLOBAL_FCN: global function(s) (exported to other modules)
\**************************************************************************************************/
extern void validate_cmd(Bool neutral, Bool up, Bool down, Bool endstop_top, Bool endstop_bottom,
    Bool * Spwlib1_validated_neutral, Bool * Spwlib1_validated_up, Bool * Spwlib1_validated_down);

/**************************************************************************************************\
   GlobalStep: Default function class for not static model step functions
\**************************************************************************************************/
extern void PowerWindowController(void);

#ifdef __cplusplus
}
#endif

#endif /* POWERWINDOWCONTROLLER_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
